# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'greeting.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(644, 452)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 50, 241, 51))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 160, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.nameTextBox = QtWidgets.QLineEdit(self.centralwidget)
        self.nameTextBox.setGeometry(QtCore.QRect(220, 160, 231, 41))
        self.nameTextBox.setObjectName("nameTextBox")
        self.greetButton = QtWidgets.QPushButton(self.centralwidget)
        self.greetButton.setGeometry(QtCore.QRect(220, 230, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.greetButton.setFont(font)
        self.greetButton.setObjectName("greetButton")
        self.messageLabel = QtWidgets.QLabel(self.centralwidget)
        self.messageLabel.setGeometry(QtCore.QRect(220, 350, 241, 51))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(25)
        self.messageLabel.setFont(font)
        self.messageLabel.setObjectName("messageLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 644, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Greeting App"))
        self.label_2.setText(_translate("MainWindow", "Name"))
        self.greetButton.setText(_translate("MainWindow", "Greet"))
        self.messageLabel.setText(_translate("MainWindow", "Hello"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
